Escape URI path
openregister/openregister-ruby-client pull request #11
Opened 2017-11-01 11:24 UTC by gidsg

## Before
Querying a key containing a non URL safe character such as a whitespace would cause an exception
```
> OpenRegister.record 'country', 'S U', :beta
URI::InvalidURIError: bad URI(is not URI?): https://country.beta.openregister.org/record/S U.tsv
```

## After 
The query is URL escaped

```
> OpenRegister.record 'country', 'S U', :beta
https://country.beta.openregister.org/record/S%20U.tsv - 404 Not Found
 => nil 

```

2017-11-01 13:13 UTC, arnau reviewed
As far as I know, a URI does not allow an unencoded space. Is this the best place to use `URI.escape`?

2017-11-03 10:06 UTC, gidsg commented
...yes, the client argument gets turned into a URI. So in order to allow this query and not throw an exception we need to escape URI escape the user input.

2017-11-03 10:13 UTC, arnau approved these changes

2017-11-03 10:18 UTC, arnau requested changes
Actually, could you add some unit tests to cover this use case please?

2017-11-27 16:04 UTC, gidsg commented
...ok I added some tests now, please may you take another look @arnau?

2017-11-28 08:43 UTC, arnau approved these changes
Although strictly speaking you are testing what you added, seems like a good opportunity to add tests to cover all possible outcomes of this function. It has quite a few paths worth documenting.

2017-11-28 11:30 UTC, merged